apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sidecars.incubation.jingnanzhou.io
spec:
  group: incubation.jingnanzhou.io
  version: v1alpha1
  names:
    kind: Sidecar
    plural: sidecars
    singular: sidecar
  scope: Namespaced
