apiVersion: v1
name: sidecar-op
version: 1.2.5
appVersion: 1.2.5
description: Helm chart for all sidecar injectors
keywords:
  - sidecar
  - istio
sources:
  - http://github.com/jingnanzhou/sidecar-operator
engine: gotpl
