{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-sidecar-injector
  namespace: {{ template "sidecar-operator.ns" . }}
  labels:
    app: {{ template "sidecar-injector.name" . }}
    release: {{ .Release.Name }}
    istio: sidecar-injector
spec:
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
  selector:
    matchLabels:
      app: {{ template "sidecar-injector.name" . }}
      release: {{ .Release.Name }}
      istio: sidecar-injector
{{- end }}
