apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  config: |
    policy: enabled
    alwaysInjectSelector:
      []

    neverInjectSelector:
      []

    template: |-
      containers:
        - name: sidecar-nginx
          image: "{{ .Values.global.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configmap


  values: |
    {"global":{"image":"nginx:1.12.2"}}
