apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.jingnan.io
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: istio-system
        path: "/inject"
      caBundle: ""
#      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
#    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
