apiVersion: batch/v1
kind: Job
metadata:
  namespace: sidecar-system
  name: secret-job
spec:
  template:
    spec:
      serviceAccountName: sidecar-service-account
      containers:
      - name: secret
        image: caasguru/secret
        command: ["secret.sh",  "--namespace", "sidecar-system"]
#        args:
#          - "--namespace"
#          - "default"

        imagePullPolicy: Always
      restartPolicy: OnFailure
