apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-service-account
  namespace: sidecar-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecar-injector-job
  labels:
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sidecar-job-binding
subjects:
- kind: ServiceAccount
  name: sidecar-service-account
  namespace: sidecar-system
roleRef:
  kind: ClusterRole
  name: sidecar-injector-job
  apiGroup: rbac.authorization.k8s.io
