apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sidecarWebhookService }}
  namespace: {{ template "sidecar-operator.ns" . }}
  labels:
    app: {{ .Values.global.appName}}
spec:
  ports:
  - port: 443
  selector:
    app: {{ .Values.global.appName }}
